apiVersion: "xcl.example.io/v1"
kind: VpcNatTunnel
metadata:
  name: gre1
  namespace: ns2
spec:
  remoteCluster: "cluster2"      
  remoteVpc: "test-vpc-2"         
  interfaceAddr: "10.100.0.1/24" 
  localVpc: "test-vpc-2"         