apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: external-network
  namespace: kube-system
spec:
  config: '{
    "type": "macvlan",
    "cniVersion": "0.3.0",
    "mode": "bridge",
    "master": "ens3", 
    "ipam": {
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "external-network.kube-system"
    }
  }'

---
apiVersion: example.io/v1
kind: Subnet
metadata:
  name: external-network
spec:
  provider: ovn-vpc-external-network.kube-system
  protocol: IPv4
  cidrBlock: 10.10.1.0/24
  gateway: 10.10.1.1
  excludeIps:
    - 10.10.1.1-10.10.1.100
